# http://justcramer.com/2012/05/03/using-travis-ci/

language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python -c "print 'No tests yet, but sure there will be some';"
