DROP TABLE IF EXISTS lyric_comment;
DROP TABLE IF EXISTS lyric;
DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS album;

DROP TABLE IF EXISTS band_genres;
DROP TABLE IF EXISTS band;
DROP TABLE IF EXISTS genre;
